# Generated by Django 4.0.4 on 2022-04-23 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=70, verbose_name="Nombre del docente"),
                ),
                (
                    "apellido",
                    models.CharField(
                        max_length=70, verbose_name="Apellido del docente"
                    ),
                ),
                (
                    "fecha_nacimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de nacimiento"
                    ),
                ),
                (
                    "usuario",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Nombre de usuario"
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        verbose_name="Contraseña del docente",
                    ),
                ),
            ],
            options={
                "verbose_name": "docente",
                "verbose_name_plural": "docentes",
            },
        ),
    ]
