# Generated by Django 4.0.4 on 2022-04-23 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cursos", "__first__"),
        ("docentes", "__first__"),
        ("notas", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alumno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=70, verbose_name="Nombre del alumno"),
                ),
                (
                    "apellido",
                    models.CharField(max_length=70, verbose_name="Apellido del alumno"),
                ),
                (
                    "fecha_nacimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de nacimiento"
                    ),
                ),
                (
                    "usuario",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Nombre de usuario"
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Contraseña del alumno"
                    ),
                ),
                ("cursos", models.ManyToManyField(blank=True, to="cursos.curso")),
                ("docentes", models.ManyToManyField(blank=True, to="docentes.docente")),
                ("notas", models.ManyToManyField(blank=True, to="notas.nota")),
            ],
            options={
                "verbose_name": "alumno",
                "verbose_name_plural": "alumnos",
            },
        ),
    ]
