# Generated by Django 4.0.4 on 2022-04-23 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cursos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "practicas",
                    models.FloatField(verbose_name="Calificaciones practicas"),
                ),
                (
                    "parciales",
                    models.FloatField(verbose_name="Calificaciones practicas"),
                ),
                ("examen", models.FloatField(verbose_name="Calificaciones practicas")),
                ("promedio", models.FloatField(verbose_name="Promedio final")),
                ("cursos", models.ManyToManyField(blank=True, to="cursos.curso")),
            ],
            options={
                "verbose_name": "nota",
                "verbose_name_plural": "nota",
            },
        ),
    ]
