# Generated by Django 4.0.4 on 2022-04-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("docentes", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Nombre del curso"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descripcion del curso"
                    ),
                ),
                (
                    "duracion",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Duracion del curso"
                    ),
                ),
                ("docentes", models.ManyToManyField(blank=True, to="docentes.docente")),
            ],
            options={
                "verbose_name": "curso",
                "verbose_name_plural": "cursos",
            },
        ),
    ]
